name: Sync Fork

on:
  schedule:
    - cron: '* */3 * * *'
  ## 手动
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          owner: vamoschuck # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch

  parse-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create file
        run: |
          ls -a
          mkdir .suke
          cat  M3U | awk '{match($0,"group-title=\"") ;print substr($0,RSTART+RLENGTH)}'  > ./.suke/format.txt
          awk '{if(NR%2==0){printf $0 "\n"}else{printf "%s：",$0}}' ./.suke/format.txt  > ./.suke/line.txt
          ls .suke -a
      - name : push
        run: |
          ls -a
