name: Sync Fork

on:
  push:
    branches: [ "main" ]
  ## 手动
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          owner: vamoschuck # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch

  parse-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create file
        run: |
          ls -a
          version=`date +%Y%m%d`
          mv ./.suke/line.txt ./back/$version-line.txt
          rm -rf ./.suke
          mkdir ./.suke
          awk NF M3U > m3u.txt
          sed -r '/#htt/d'  m3u.txt > m3u2.txt
          cat  m3u2.txt |tail -n +2 | awk '{match($0,"group-title=") ;print substr($0,RSTART+RLENGTH)}'  > ./.suke/format.txt
          awk  '{if(NR%2==0){printf $0 "\n"}else{printf "%s,=",$0}}' ./.suke/format.txt  > ./.suke/line.txt
          cat ./.suke/line.txt | grep '121.51.249.6\|111.32.169.223\|live.shaoxing.com.cn\|kan0512.com\|live.sctvcloud.com' > ./.suke/temp.txt
          mv ./.suke/temp.txt ./.suke/line.txt
          ls .suke -a
          cat ./.suke/line.txt
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.MY_GIT_TOKEN }}
          push-branch: main
          commit-message: format data
          # Force push.
          force-push: true
          # Specific files to add.
          files: .suke .suke/format.txt .suke/line.txt back/*
          # Committer email. Default is ${name}@users.noreply.github.com
          email: 1215618342@qq.com
          # Committer name. Default is name of the person or app that initiated the workflow.
          name: wangsrGit119
